"use strict";
const fs=require("fs"),path=require("path");
const N=4,NC=3,R=8,M=34,MIN=-2,MAX=6,E=2,T=2,GAMES=10000;
const TYPES=["S0","S1","S2","S2+","S2-"], RULES=["A","B"];
function rng32(a){return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
const ri=(r,n)=>Math.floor(r()*n),avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0,cl=(x,a,b)=>Math.max(a,Math.min(b,x));
function blank(){return{games:0,wins:0,score:0,score2:0,price:0,sold:0,won:0,profit:0,over:0,curse:0,blocked:0,spend:0,cashHalf:0,cashBack:0,cashLast2:0,estN:0,abs:0,overEst:0,underEst:0,limitUp:0,limitDown:0,limitSame:0,correctLimit:0,wrongLimit:0,goodUp:0,badDown:0,posN:0,posProfit:0,negN:0,negProfit:0,bands:{},obsPos:0,effSig:0}}
function band(v){return v<=0?"bad":v<=4?"slightlyBad":v<=8?"middle":v<=12?"slightlyGood":"good"}
function inferLens(hist,q){const sc=Array(NC).fill(0);for(const h of hist){const x=h.per[q];if(!x.bid)continue;const zeal=x.top-h.total/2;for(let j=0;j<NC;j++)sc[j]+=zeal*(h.v[j]-E)}const mx=Math.max(...sc),z=sc.map(x=>Math.exp((x-mx)/12)),s=z.reduce((a,b)=>a+b,0);return z.map(x=>x/s)}
function estimate(g,a,p,type){const own=a.v[g.lens[p]],base=own+E*(NC-1);if(type==="S0")return{est:base,pos:0,neg:0,eff:0};
 const sig=[];for(let q=0;q<N;q++){if(q===p)continue;const x=a.per[q];if(!x.bid&&!x.drop)continue;let pos=g.rule==="B"?g.lens[q]:null;if(g.rule==="A"&&g.hist.length>=2){const pr=inferLens(g.hist,q);pos=pr.indexOf(Math.max(...pr))}const edge=x.drop?x.refused-1:x.top;const face=cl((edge+1.1-E*(NC-1))/(1+T),MIN,MAX);sig.push({pos,face,positive:face>E})}
 if(type==="S1"){if(!sig.length)return{est:base,pos:0,neg:0,eff:0};const imp=avg(sig.map(x=>x.face-E));return{est:base+.34*imp,pos:imp>0?imp:0,neg:imp<0?imp:0,eff:sig.length}}
 const by=new Map;for(let si=0;si<sig.length;si++){const s=sig[si],k=s.pos==null?`u${si}`:`p${s.pos}`;if(s.pos===g.lens[p])continue;if(!by.has(k))by.set(k,[]);by.get(k).push(s.face)}let up=0,dn=0;for(const xs of by.values()){const d=avg(xs)-E;if(d>0)up+=d;else dn+=d}if(type==="S2+")dn=0;if(type==="S2-")up=0;return{est:base+.36*(up+dn),pos:up,neg:dn,eff:by.size}}
function npcEstimate(g,a,p){let est=a.v[g.lens[p]]+E*(NC-1);const drops=[];for(let q=0;q<N;q++)if(q!==p&&!a.live.includes(q)){const x=a.per[q];drops.push(x.top-T*E)}if(drops.length){const im=Math.min(...drops);if(im<est)est-=(est-im)*.5*(drops.length/(N-1))}if(g.hist.length>=2){let z=0,w=0;for(const q of a.live){if(q===p||!a.per[q].bid)continue;const pr=inferLens(g.hist,q),nw=1-pr[g.lens[p]];z+=(a.per[q].top-T*E)*nw;w+=nw}if(w>.2){const im=z/w;est+=(im-est)*(im<est?.45:.15)}}return est}
function lim(g,a,p,type){const est=type==="S3"?npcEstimate(g,a,p):estimate(g,a,p,type).est,nr=a.live.length-1,curse=(nr>0?nr/(N-1):1)*E*(NC-1)*.42;return Math.round(est+T*a.v[g.lens[p]]-curse)}
function play(rule,types,seed){const rl=rng32(seed),lens=Array.from({length:N},()=>ri(rl,NC)),lots=Array.from({length:R},()=>Array.from({length:NC},()=>MIN+ri(rl,MAX-MIN+1))),money=Array(N).fill(M),assets=Array.from({length:N},()=>[]),hist=[],logs=[],cash=[];for(let r=0;r<R;r++){const v=lots[r],total=v.reduce((a,b)=>a+b,0),live=[0,1,2,3].filter(p=>money[p]>=1),per=Array.from({length:N},()=>({top:0,bid:false,drop:false,refused:null})),a={v,total,live,per,price:0,last:-1,cur:live[ri(rl,live.length)]},g={rule,lens,hist};const first=Array(N).fill(null),before=money.slice();let guard=0;
 while(a.live.length>1&&guard++<300){const p=a.cur,type=types[p],e=type==="S3"?{est:npcEstimate(g,a,p),pos:0,neg:0,eff:0}:estimate(g,a,p,type),base=a.v[lens[p]]+E*(NC-1),L=lim(g,a,p,type),baseCurse=((a.live.length-1)/(N-1))*E*(NC-1)*.42;first[p]={est:e.est,base,limit:L,baseLimit:Math.round(base+T*a.v[lens[p]]-baseCurse),pos:e.pos,neg:e.neg,eff:e.eff};const next=a.price+1;if(next<=L&&next<=money[p]){a.price=next;a.last=p;per[p].top=next;per[p].bid=true}else{if(next<=L&&next>money[p])per[p].blocked=true;per[p].drop=true;per[p].refused=next;a.live=a.live.filter(x=>x!==p)}if(a.live.length<=1)break;let c=p;do{c=(c+1)%N}while(!a.live.includes(c));if(c===a.last)break;a.cur=c}
 const w=a.price>0?(a.live.length===1?a.live[0]:a.last):-1,profits=Array(N).fill(null);if(w>=0){const val=total+T*v[lens[w]];profits[w]=val-a.price;money[w]-=a.price;assets[w].push(val)}logs.push({round:r,v,total,observedPositions:new Set(lens).size,price:a.price,w,profits,before,after:money.slice(),first,per:per.map(x=>({...x}))});hist.push({v,total,per:per.map(x=>({...x}))});cash.push(money.slice())}const score=money.map((m,p)=>m+assets[p].reduce((a,b)=>a+b,0));return{lens,lots,logs,cash,money,score}}
function addResult(m,game,p,type){m.games++;const mx=Math.max(...game.score),ties=game.score.filter(x=>x===mx).length;if(game.score[p]===mx)m.wins+=1/ties;m.score+=game.score[p];m.score2+=game.score[p]**2;m.cashHalf+=game.cash[3][p];m.cashBack+=game.cash[4][p];m.cashLast2+=game.cash[5][p];m.spend+=M-game.money[p];for(const x of game.logs){m.price+=x.price;if(x.w>=0)m.sold++;if(x.w===p){m.won++;m.profit+=x.profits[p];if(x.profits[p]<0){m.over++;m.curse++}}if(x.per[p].blocked)m.blocked++;const f=x.first[p];if(!f)continue;const err=f.est-x.total,be=f.base-x.total,b=band(x.total);m.estN++;m.abs+=Math.abs(err);m.overEst+=Math.max(0,err);m.underEst+=Math.max(0,-err);m.obsPos+=x.observedPositions;m.effSig+=f.eff;if(!m.bands[b])m.bands[b]={n:0,abs:0,baseAbs:0};m.bands[b].n++;m.bands[b].abs+=Math.abs(err);m.bands[b].baseAbs+=Math.abs(be);const d=f.limit-f.baseLimit;if(d>0)m.limitUp++;else if(d<0)m.limitDown++;else m.limitSame++;const goodDir=(d>0&&x.total>f.base)||(d<0&&x.total<f.base);if(d&&goodDir)m.correctLimit++;else if(d)m.wrongLimit++;if(d>0&&x.total>8)m.goodUp++;if(d<0&&x.total<5)m.badDown++;if(f.pos>0){m.posN++;if(x.w===p)m.posProfit+=x.profits[p]}if(f.neg<0){m.negN++;if(x.w===p)m.negProfit+=x.profits[p]}}}
function fin(m){const p=m.wins/m.games,se=Math.sqrt(p*(1-p)/m.games),score=m.score/m.games,sd=Math.sqrt(m.score2/m.games-score*score);const bands={};for(const[k,x]of Object.entries(m.bands))bands[k]={n:x.n,mae:x.abs/x.n,baseMAE:x.baseAbs/x.n,improvement:(x.baseAbs-x.abs)/x.n};return{games:m.games,winRate:p,winCI95:[p-1.96*se,p+1.96*se],meanScore:score,scoreSD:sd,avgPrice:m.price/Math.max(1,m.sold),profitPerWin:m.profit/Math.max(1,m.won),overpayRate:m.over/Math.max(1,m.won),cashHalf:m.cashHalf/m.games,cashBackStart:m.cashBack/m.games,cashBeforeLast2:m.cashLast2/m.games,fundsBlockedPerGame:m.blocked/m.games,spend:m.spend/m.games,estimateMAE:m.abs/m.estN,overestimate:m.overEst/m.estN,underestimate:m.underEst/m.estN,observedPositions:m.obsPos/m.estN,effectiveSignals:m.effSig/m.estN,bands,limitUpRate:m.limitUp/m.estN,limitDownRate:m.limitDown/m.estN,limitSameRate:m.limitSame/m.estN,correctDirectionRate:m.correctLimit/Math.max(1,m.correctLimit+m.wrongLimit),goodStoneUpPerGame:m.goodUp/m.games,badStoneDownPerGame:m.badDown/m.games,positiveSignalLots:m.posN/m.games,positiveSignalProfit:m.posProfit/Math.max(1,m.posN),negativeSignalLots:m.negN/m.games,negativeSignalProfit:m.negProfit/Math.max(1,m.negN)}}
function paired(rule){const agg=Object.fromEntries(TYPES.map(t=>[t,blank()])),pairs={S2vsS0:{upEst:0,upPrice:0,profitDelta:0,n:0,goodOnly:0,badAvoid:0,readBadBuy:0,correctLost:0,valuePrice:0,noFuture:0,extraSpend:0,missedFuture:0},S2vsS1:{cheaperGood:0,lessOverpay:0,n:0}};for(let i=0;i<GAMES;i++){const games={};for(const t of TYPES){games[t]=play(rule,[t,"S3","S3","S3"],700000+i);addResult(agg[t],games[t],0,t)}const a=games.S0,b=games.S1,s=games.S2;for(let r=0;r<R;r++){const x=a.logs[r],y=s.logs[r],z=b.logs[r],f0=x.first[0],f2=y.first[0],pe=f2&&f0?f2.est-f0.est:0,pp=y.price-x.price,pr=(y.w===0?(y.profits[0]||0):0)-(x.w===0?(x.profits[0]||0):0);if(pe>0){pairs.S2vsS0.upEst+=pe;pairs.S2vsS0.upPrice+=pp;pairs.S2vsS0.profitDelta+=pr;pairs.S2vsS0.n++}if(y.w===0&&x.w!==0&&y.profits[0]>0)pairs.S2vsS0.goodOnly++;if(y.w!==0&&x.w===0&&x.profits[0]<0)pairs.S2vsS0.badAvoid++;if(y.w===0&&y.profits[0]<0&&x.w!==0)pairs.S2vsS0.readBadBuy++;if(f2&&Math.abs(f2.est-y.total)<Math.abs(f2.base-y.total)&&y.w!==0&&y.total+T*y.v?.[0]-y.price>0)pairs.S2vsS0.correctLost++;if(y.w===0&&Math.abs(f2.est-y.total)<Math.abs(f2.base-y.total)&&Math.abs(y.profits[0])<1)pairs.S2vsS0.valuePrice++;const extra=Math.max(0,x.after[0]-y.after[0]);pairs.S2vsS0.extraSpend+=extra;if(extra>0&&r<R-1){const future=s.logs.slice(r+1).some(q=>q.total+T*q.v[s.lens[0]]-q.price>0&&q.w!==0);if(future)pairs.S2vsS0.missedFuture++}if(y.w===0&&z.w===0&&y.profits[0]>0&&y.price<z.price)pairs.S2vsS1.cheaperGood++;if((y.w!==0||y.profits[0]>=0)&&(z.w===0&&z.profits[0]<0))pairs.S2vsS1.lessOverpay++;pairs.S2vsS1.n++}}
 const out={strategies:{}};for(const[k,m]of Object.entries(agg))out.strategies[k]=fin(m);const q=pairs.S2vsS0;out.counterfactual={S2vsS0:{meanPositiveEstimateLift:q.upEst/Math.max(1,q.n),meanPriceLift:q.upPrice/Math.max(1,q.n),meanProfitChange:q.profitDelta/Math.max(1,q.n),priceAbsorptionRate:q.upPrice/Math.max(1,q.upEst),S2OnlyGoodBuyPerGame:q.goodOnly/GAMES,S2OnlyBadAvoidPerGame:q.badAvoid/GAMES,readCausedBadBuyPerGame:q.readBadBuy/GAMES,correctButPriceAtValuePerGame:q.valuePrice/GAMES,meanExtraSpend:q.extraSpend/GAMES,missedFuturePositiveAfterExtraSpendPerGame:q.missedFuture/GAMES},S2vsS1:{cheaperGoodPerGame:pairs.S2vsS1.cheaperGood/GAMES,lessOverpayPerGame:pairs.S2vsS1.lessOverpay/GAMES}};return out}
function market(){const out={};for(let k=1;k<=4;k++){const ms=blank(),all=blank();for(let i=0;i<GAMES;i++){const types=Array.from({length:N},(_,p)=>p<k?"S2":"S3"),g=play("B",types,900000+i);for(let p=0;p<N;p++)addResult(p<k?ms:all,g,p,types[p])}out[k]={s2:fin(ms),others:k<4?fin(all):null}}return out}
const results={meta:{gamesPerCell:GAMES,seed:"fixed paired common random numbers",rules:"seri.html v1.4, 4 players"},paired:{A:paired("A"),B:paired("B")},marketS2Count:market()};fs.writeFileSync(path.join(__dirname,"seri_read_value_conversion_results.json"),JSON.stringify(results,null,2));console.log("wrote seri_read_value_conversion_results.json");
