"use strict";
/* 影の競り: 私的価値倍率(T=2/1) × 観測位置(非公開/公開) 2×2検証。
   製品コードから独立。意思決定関数には現在原石の未知面・真の総価値を渡さない。 */
const fs=require("fs"),path=require("path");
const N=4,NC=3,ROUNDS=8,MONEY=34,MIN=-2,MAX=6,E=2,ALPHA=.25;
const GROUPS=10,FULL_GAMES=250,SMOKE_GAMES=10,TCRIT9=2.262;
const RULES={A3:{publicPos:false,T:2},B3:{publicPos:true,T:2},A2:{publicPos:false,T:1},B2:{publicPos:true,T:1}};
const METRICS=["winRate","meanScore","profitPerWin","overpayRate","meanCash","avgPrice","lotsPerGame","badAvoidPerGame","goodPassPerGame","fundsBlockedPerGame","estimateMAE","infoUsePerGame"];
function rng32(a){return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
const ri=(r,n)=>Math.floor(r()*n),avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0,cl=(x,a,b)=>Math.max(a,Math.min(b,x));
function lensPosterior(hist,q){const sc=Array(NC).fill(0);for(const h of hist){const x=h.per[q];if(!x.bid)continue;const zeal=x.top-h.total/2;for(let j=0;j<NC;j++)sc[j]+=zeal*(h.v[j]-E)}const mx=Math.max(...sc),z=sc.map(x=>Math.exp((x-mx)/12)),s=z.reduce((a,b)=>a+b,0);return z.map(x=>x/s)}
function positionProb(view,q,usePublic){if(usePublic&&view.publicPositions)return Array.from({length:NC},(_,j)=>j===view.publicPositions[q]?1:0);return view.hist.length>=2?lensPosterior(view.hist,q):Array(NC).fill(1/NC)}
function signals(view,T){const out=[];for(let q=0;q<N;q++){if(q===view.p)continue;const x=view.per[q];if(!x.bid&&!x.drop)continue;const edge=x.drop?x.refused-1:x.top;const face=cl((edge+1.1-E*(NC-1))/(1+T),MIN,MAX);out.push({q,face,alive:view.live.includes(q),top:x.top})}return out}
function estimate(view,type,T,usePublic){const base=view.own+E*(NC-1);if(type==="S0")return{est:base,used:false};const ss=signals(view,T);if(type==="S1"){if(!ss.length)return{est:base,used:false};const implied=avg(ss.map(s=>s.top-T*E)),k=implied<base?.35:.22;return{est:base+(implied-base)*k,used:true}}
 if(type==="S2"){let delta=0,evidence=0;for(let j=0;j<NC;j++){if(j===view.myLens)continue;let num=0,den=0,none=1;for(const s of ss){const p=positionProb(view,s.q,usePublic)[j];num+=p*s.face;den+=p;none*=1-p}if(den>1e-9){const w=1-none;delta+=w*(num/den-E);evidence+=w}}return{est:base+ALPHA*.72*delta,used:evidence>1e-9}}
 throw new Error("unknown estimate type "+type)}
function npcEstimate(view,T){let est=view.own+E*(NC-1),drops=[];for(let q=0;q<N;q++)if(q!==view.p&&!view.live.includes(q)){const x=view.per[q];drops.push(x.top-T*E)}if(drops.length){const im=Math.min(...drops);if(im<est)est-=(est-im)*.5*(drops.length/(N-1))}if(view.hist.length>=2){let z=0,w=0;for(const q of view.live){if(q===view.p||!view.per[q].bid)continue;const pr=lensPosterior(view.hist,q),nw=1-pr[view.myLens];z+=(view.per[q].top-T*E)*nw;w+=nw}if(w>.2){const im=z/w;est+=(im-est)*(im<est?.45:.15)}}return est}
function decision(view,type,T,usePublic){const x=type==="S3"?{est:npcEstimate(view,T),used:true}:estimate(view,type,T,usePublic);const rivals=view.live.length-1,curse=(rivals>0?rivals/(N-1):1)*E*(NC-1)*.42;return{limit:Math.round(x.est+T*view.own-curse),est:x.est,used:x.used}}
function empty(){return{games:0,wins:0,score:0,score2:0,cash:0,sold:0,price:0,won:0,profit:0,over:0,badAvoid:0,goodPass:0,blocked:0,estN:0,abs:0,infoUse:0}}
function add(a,b){for(const k of Object.keys(a))a[k]+=b[k]||0}
function finalize(m){const p=m.wins/m.games,mu=m.score/m.games,sd=Math.sqrt(Math.max(0,m.score2/m.games-mu*mu));return{games:m.games,winRate:p,winGameCI95:[p-1.96*Math.sqrt(Math.max(p*(1-p),1e-12)/m.games),p+1.96*Math.sqrt(Math.max(p*(1-p),1e-12)/m.games)],meanScore:mu,scoreSD:sd,profitPerWin:m.profit/Math.max(1,m.won),overpayRate:m.over/Math.max(1,m.won),meanCash:m.cash/m.games,avgPrice:m.price/Math.max(1,m.sold),lotsPerGame:m.won/m.games,badAvoidPerGame:m.badAvoid/m.games,goodPassPerGame:m.goodPass/m.games,fundsBlockedPerGame:m.blocked/m.games,estimateMAE:m.abs/Math.max(1,m.estN),infoUsePerGame:m.infoUse/m.games}}
function play(ruleKey,types,envSeed,readerMode="on"){const cfg=RULES[ruleKey],r=rng32(envSeed),lenses=Array.from({length:N},()=>ri(r,NC)),lots=Array.from({length:ROUNDS},()=>Array.from({length:NC},()=>MIN+ri(r,MAX-MIN+1))),starters=Array.from({length:ROUNDS},()=>ri(r,N)),money=Array(N).fill(MONEY),assets=Array.from({length:N},()=>[]),hist=[],pm=Array.from({length:N},()=>empty());
 for(let round=0;round<ROUNDS;round++){const v=lots[round];if(v.some(x=>x<MIN||x>MAX))throw Error("value invariant");const total=v.reduce((a,b)=>a+b,0),live=Array.from({length:N},(_,i)=>i).filter(i=>money[i]>=1),per=Array.from({length:N},()=>({top:0,bid:false,drop:false,refused:null}));if(!live.length)break;let cur=live[starters[round]%live.length],price=0,last=-1,guard=0;
  while(live.length>1&&guard++<400){const p=cur,type=types[p],view={p,own:v[lenses[p]],myLens:lenses[p],live:live.slice(),per:per.map(x=>({...x})),hist,publicPositions:cfg.publicPos?lenses:null};const usePublic=cfg.publicPos&&!(type==="S2"&&readerMode==="off"),d=decision(view,type,cfg.T,usePublic),base=view.own+E*(NC-1);pm[p].estN++;pm[p].abs+=Math.abs(d.est-total);if(d.used&&Math.abs(d.est-base)>1e-12)pm[p].infoUse++;const next=price+1;if(next<=d.limit&&next<=money[p]){price=next;last=p;per[p].top=next;per[p].bid=true}else{if(next<=d.limit&&next>money[p])pm[p].blocked++;per[p].drop=true;per[p].refused=next;live.splice(live.indexOf(p),1)}if(live.length<=1)break;let c=p;do{c=(c+1)%N}while(!live.includes(c));if(c===last)break;cur=c}
  if(guard>=400)throw Error("auction guard");const winner=price>0?(live.length===1?live[0]:last):-1;if(winner>=0){const val=total+cfg.T*v[lenses[winner]],gain=val-price;money[winner]-=price;if(money[winner]<0)throw Error("negative money");assets[winner].push(val);pm[winner].won++;pm[winner].profit+=gain;if(gain<0)pm[winner].over++}for(let p=0;p<N;p++){if(p!==winner&&winner>=0){const surplus=total+cfg.T*v[lenses[p]]-price;if(surplus<0&&per[p].drop)pm[p].badAvoid++;if(surplus>0&&per[p].drop)pm[p].goodPass++}if(winner>=0){pm[p].sold++;pm[p].price+=price}}hist.push({v:v.slice(),total,per:per.map(x=>({...x}))})}
 const score=money.map((m,p)=>m+assets[p].reduce((a,b)=>a+b,0));if(score.some(x=>!Number.isFinite(x)))throw Error("score finite");const mx=Math.max(...score),ties=score.filter(x=>x===mx).length;for(let p=0;p<N;p++){pm[p].games=1;pm[p].score=score[p];pm[p].score2=score[p]*score[p];pm[p].cash=money[p];if(score[p]===mx)pm[p].wins=1/ties}return pm}
function seedBase(group,rotation,index,experiment){return 1300713+group*100003+rotation*1009+index*17+experiment*9000001}
function groupedCI(values){const mu=avg(values),sd=Math.sqrt(values.reduce((s,x)=>s+(x-mu)**2,0)/(values.length-1)),se=sd/Math.sqrt(values.length);return{mean:mu,seedSD:sd,ci95:[mu-TCRIT9*se,mu+TCRIT9*se],seedValues:values}}
function strategyMap(rotation){const names=["S0","S1","S2","S3"];return Array.from({length:N},(_,seat)=>names[(seat-rotation+N)%N])}
function experiment1(games){const perRule={},seedRule={};for(const k of Object.keys(RULES)){perRule[k]={S0:empty(),S1:empty(),S2:empty(),S3:empty()};seedRule[k]=[]}
 for(let g=0;g<GROUPS;g++){const local={};for(const k of Object.keys(RULES))local[k]={S0:empty(),S1:empty(),S2:empty(),S3:empty()};for(let rot=0;rot<N;rot++){const types=strategyMap(rot);for(let i=0;i<games;i++){const seed=seedBase(g,rot,i,1);for(const k of Object.keys(RULES)){const pm=play(k,types,seed);for(let p=0;p<N;p++)add(local[k][types[p]],pm[p])}}}for(const k of Object.keys(RULES)){for(const s of Object.keys(local[k]))add(perRule[k][s],local[k][s]);seedRule[k].push({seedGroup:g,strategies:Object.fromEntries(Object.entries(local[k]).map(([s,m])=>[s,finalize(m)]))})}console.log(`experiment1 seed-group ${g+1}/${GROUPS}`)}
 const summary={};for(const k of Object.keys(RULES))summary[k]={strategies:Object.fromEntries(Object.entries(perRule[k]).map(([s,m])=>[s,finalize(m)])),seedGroups:seedRule[k]};const effects={};for(const metric of METRICS){const vals={B3_A3:[],B2_A2:[],A2_A3:[],B2_B3:[],interaction:[]};for(let g=0;g<GROUPS;g++){const x=k=>seedRule[k][g].strategies.S2[metric];vals.B3_A3.push(x("B3")-x("A3"));vals.B2_A2.push(x("B2")-x("A2"));vals.A2_A3.push(x("A2")-x("A3"));vals.B2_B3.push(x("B2")-x("B3"));vals.interaction.push((x("B2")-x("A2"))-(x("B3")-x("A3")))}effects[metric]=Object.fromEntries(Object.entries(vals).map(([k,v])=>[k,groupedCI(v)]))}return{summary,effects}}
function experiment2(games){const modes=["on","off"],rules=["B3","B2"],sum={},groups={};for(const k of rules){sum[k]={on:empty(),off:empty()};groups[k]={on:[],off:[]}}
 for(let g=0;g<GROUPS;g++){const local={};for(const k of rules)local[k]={on:empty(),off:empty()};for(let seat=0;seat<N;seat++)for(let i=0;i<games;i++){const seed=seedBase(g,seat,i,2);for(const k of rules)for(const mode of modes){const types=Array(N).fill("S3");types[seat]="S2";const pm=play(k,types,seed,mode);add(local[k][mode],pm[seat])}}for(const k of rules)for(const mode of modes){add(sum[k][mode],local[k][mode]);groups[k][mode].push({seedGroup:g,...finalize(local[k][mode])})}console.log(`experiment2 seed-group ${g+1}/${GROUPS}`)}
 const summary={},effects={};for(const k of rules){summary[k]={};for(const mode of modes)summary[k][mode]={overall:finalize(sum[k][mode]),seedGroups:groups[k][mode]};effects[k]={};for(const metric of METRICS){const d=Array.from({length:GROUPS},(_,g)=>groups[k].on[g][metric]-groups[k].off[g][metric]);effects[k][metric]=groupedCI(d)}}return{summary,effects}}
function audit(result,smoke){function walk(x,p="root"){if(typeof x==="number"&&!Number.isFinite(x))throw Error("nonfinite "+p);if(Array.isArray(x))x.forEach((v,i)=>walk(v,p+"/"+i));else if(x&&typeof x==="object")Object.entries(x).forEach(([k,v])=>walk(v,p+"/"+k))}walk(result);if(!smoke){const total=Object.values(result.experiment1.summary).reduce((n,r)=>n+r.strategies.S0.games,0)+Object.values(result.experiment2.summary).reduce((n,r)=>n+r.on.overall.games+r.off.overall.games,0);if(total!==80000)throw Error("game count invariant "+total)}return true}
function main(){const smoke=process.argv.includes("--smoke"),games=smoke?SMOKE_GAMES:FULL_GAMES,t0=Date.now();console.log(`mode=${smoke?"smoke":"full"} games-per-microcell=${games}`);const result={meta:{createdAt:new Date().toISOString(),mode:smoke?"smoke":"full",alpha:ALPHA,seedGroups:GROUPS,gamesPerCell:games,players:N,rounds:ROUNDS,commonRandomNumbers:true,tieHandling:"fractional win shared among tied first-place players",decisionInformation:"own current face; public bid/drop/cash state; revealed past lots; positions only in public conditions",rules:RULES},experiment1:experiment1(games),experiment2:experiment2(games)};audit(result,smoke);result.meta.runtimeMs=Date.now()-t0;if(!smoke)fs.writeFileSync(path.join(__dirname,"seri_signal_factorial_results.json"),JSON.stringify(result,null,2));console.log(`completed mode=${result.meta.mode} runtimeMs=${result.meta.runtimeMs}`)}
main();
