"use strict";
/* Independent simulation for observation-position variants. Product files are untouched. */
const fs=require("fs"), path=require("path");
const SETUP={2:{NC:3,R:6,M:30},3:{NC:3,R:6,M:30},4:{NC:3,R:8,M:34},5:{NC:4,R:10,M:38},6:{NC:4,R:12,M:38}};
const CMIN=-2,CMAX=6,E=2,T=2,PROF=[{opt:1,read:1,curse:1},{opt:1,read:1,curse:1},{opt:.85,read:1,curse:1.4},{opt:1.1,read:.3,curse:.3},{opt:.95,read:1,curse:.8},{opt:1.05,read:.6,curse:1.1}];
const RULES=["A","B","B-lite","B-history"], ALPHAS=[.25,.5,.75,1];
function rng32(a){return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
const ri=(r,n)=>Math.floor(r()*n), mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
function lensPosterior(hist,q,nc){const sc=Array(nc).fill(0);for(const h of hist){const x=h.per[q];if(!x||!x.bid)continue;const zeal=x.top-h.total/2;for(let j=0;j<nc;j++)sc[j]+=zeal*(h.v[j]-E)}const mx=Math.max(...sc),ex=sc.map(x=>Math.exp((x-mx)/12)),z=ex.reduce((a,b)=>a+b,0);return ex.map(x=>x/z)}
function visiblePosition(rule,g,p,q){if(rule==="B")return g.lens[q];if(rule==="B-lite"&&g.revealed[q])return g.lens[q];return null}
function baseEstimate(g,a,p){return a.v[g.lens[p]]+E*(g.nc-1)}
function currentSignals(g,a,p,byPos){const sig=[];for(let q=0;q<g.n;q++){if(q===p)continue;const x=a.per[q],pos=visiblePosition(g.rule,g,p,q);if(!x.bid&&!x.dropped)continue;const implied=x.top-T*E;sig.push({q,pos,implied,alive:a.live.includes(q),top:x.top,refused:x.refused})}if(!byPos)return sig;const m=new Map;for(const s of sig){const k=s.pos==null?`u${s.q}`:`p${s.pos}`;if(!m.has(k))m.set(k,[]);m.get(k).push(s)}return [...m.values()].map(xs=>({pos:xs[0].pos,implied:mean(xs.map(x=>x.implied)),alive:xs.some(x=>x.alive),top:Math.max(...xs.map(x=>x.top)),refused:mean(xs.filter(x=>x.refused!=null).map(x=>x.refused))}))}
function estimateTotal(g,a,p,type,alpha=.5){let est=baseEstimate(g,a,p),used=false,distinguished=false;
 if(type==="S0")return{est,used,distinguished};
 if(type==="S3"){const cfg=PROF[p],drops=currentSignals(g,a,p,false).filter(x=>!x.alive);if(drops.length){const imp=Math.min(...drops.map(x=>x.implied));if(imp<est){est-= (est-imp)*.5*cfg.read*(drops.length/(g.n-1));used=true}}if(g.hist.length>=2){let info=0,w=0;for(const s of currentSignals(g,a,p,false).filter(x=>x.alive&&x.top)){const pr=lensPosterior(g.hist,s.q,g.nc),nw=1-pr[g.lens[p]];info+=s.implied*nw;w+=nw}if(w>.2){const imp=info/w,k=imp<est?.45:.15;est+=(imp-est)*k*cfg.read;used=true}}return{est,used,distinguished}}
 if(type==="S1"){const ss=currentSignals(g,a,p,false);if(ss.length){const imp=.65*mean(ss.map(x=>x.implied))+.35*Math.max(...ss.map(x=>x.implied));const k=imp<est?.35:.22;est+=(imp-est)*k;used=true}return{est,used,distinguished}}
 // S2: position-aware. Same-position evidence is redundant; different positions update once each.
 let ss=currentSignals(g,a,p,true);if(g.rule==="A"){
   // use inferred identity-position probabilities after two revealed lots
   const raw=currentSignals(g,a,p,false);let num=0,den=0;for(const s of raw){const pr=g.hist.length>=2?lensPosterior(g.hist,s.q,g.nc):Array(g.nc).fill(1/g.nc);const nw=1-pr[g.lens[p]];num+=s.implied*nw;den+=nw}if(den){est+=(num/den-est)*alpha*.35;used=true}
 }else if(g.rule==="B-history"){
   // anonymous history calibrates reliability but cannot link a current person to a position.
   const raw=currentSignals(g,a,p,false);const coverage=g.posHist.reduce((z,x)=>z+(x.n>0),0)/g.nc;if(raw.length){const imp=mean(raw.map(x=>x.implied));est+=(imp-est)*alpha*.25*coverage;used=true}
 }else if(ss.length){let delta=0,k=0;for(const s of ss){if(s.pos==null||s.pos===g.lens[p])continue;const edge=s.refused!=null&&!s.alive?s.refused-1:s.top;const face=Math.max(CMIN,Math.min(CMAX,(edge+1.1-E*(g.nc-1))/(1+T)));delta+=(face-E);k++}if(k){est+=alpha*.72*delta;used=true;distinguished=new Set(ss.filter(x=>x.pos!=null).map(x=>x.pos)).size>=2}}
 return{est,used,distinguished}}
function limit(g,a,p,s){const typ=s.type,alpha=s.alpha||.5,cfg=typ==="S3"?PROF[p]:{opt:1,curse:1};const q=estimateTotal(g,a,p,typ,alpha),my=a.v[g.lens[p]],nr=a.live.length-1,curse=cfg.curse*(nr>0?nr/(g.n-1):1)*E*(g.nc-1)*.42;let lim=Math.round((q.est+T*my-curse)*cfg.opt);return{lim,diag:q}}
function policyNames(kind,n,alpha=.5){if(kind==="mixed"){const x=["S0","S1","S2","S3"];return Array.from({length:n},(_,i)=>({type:x[i%4],alpha}))}if(kind.startsWith("vs:")){const t=kind.slice(3);return Array.from({length:n},(_,i)=>i?{type:"S3"}:{type:t,alpha})}const t=kind.slice(4);return Array.from({length:n},()=>({type:t,alpha}))}
function newMetric(){return{games:0,wins:0,rankSum:0,rankDist:[0,0,0,0,0,0],score:0,score2:0,cash:0,value:0,leaderGap:0,lotsWon:0,pay:0,net:0,overpay:0,curse:0,passes:0,dropSum:0,turns:0,estN:0,estAbs:0,baseAbs:0,infoUsed:0,infoBetter:0,goodBuy:0,badAvoid:0,infoHarm:0,distinguished:0,bluffTry:0,bluffStuck:0,bluffNet:0}}
function play(n,rule,kind,alpha,lotSeed,actSeed,metrics,info){const c=SETUP[n],rl=rng32(lotSeed),ra=rng32(actSeed),lens=Array.from({length:n},()=>ri(rl,c.NC)),lots=Array.from({length:c.R},()=>Array.from({length:c.NC},()=>CMIN+ri(rl,CMAX-CMIN+1))),strats=policyNames(kind,n,alpha),money=Array(n).fill(c.M),won=Array.from({length:n},()=>[]),hist=[],revealed=Array(n).fill(rule==="B"),revealRound=Array(n).fill(rule==="B"?0:null),posHist=Array.from({length:c.NC},()=>({n:0,top:0,drop:0}));let allKnownRound=rule==="B"?0:null,histReadyRound=null;
 const g={n,nc:c.NC,rule,lens,hist,revealed,posHist};let lotWon=Array(n).fill(0),pay=Array(n).fill(0),net=Array(n).fill(0),over=Array(n).fill(0),curse=Array(n).fill(0),passes=Array(n).fill(0),dropSum=Array(n).fill(0),turns=Array(n).fill(0),diag=Array.from({length:n},()=>({n:0,abs:0,base:0,used:0,better:0,good:0,avoid:0,harm:0,dist:0,bt:0,bs:0,bn:0}));
 for(let r=0;r<c.R;r++){const v=lots[r],total=v.reduce((x,y)=>x+y,0),live=Array.from({length:n},(_,i)=>i).filter(i=>money[i]>=1),per=Array.from({length:n},()=>({top:0,bid:false,dropped:false,refused:null})),a={v,total,live,per,price:0,last:-1,cur:live.length?live[ri(rl,live.length)]:0};if(!live.length)break;let guard=0;
  while(a.live.length>1&&guard++<500){const p=a.cur,s=strats[p],x=limit(g,a,p,s),trueTot=total,base=baseEstimate(g,a,p);diag[p].n++;diag[p].abs+=Math.abs(x.diag.est-trueTot);diag[p].base+=Math.abs(base-trueTot);if(x.diag.used){diag[p].used++;diag[p].better+=Math.abs(x.diag.est-trueTot)<Math.abs(base-trueTot);if(x.diag.distinguished)diag[p].dist++}
   let lim=x.lim,bluff=false;if(s.type==="S4"&&r>=Math.ceil(c.R*.7)&&v[lens[p]]<=0&&a.live.length>=3){const scores=money.map((m,i)=>m+won[i].reduce((z,o)=>z+o.val,0)),leader=scores.indexOf(Math.max(...scores));const next=a.price+1,leadLim=leader!==p&&a.live.includes(leader)?limit(g,a,leader,{type:"S3"}).lim:-99;const safe=(total+T*v[lens[p]]-next)>=-2;if(leadLim>=next+1&&safe){lim=Math.max(lim,next+1);bluff=true;diag[p].bt++}}
   const next=a.price+1;if(next<=lim&&next<=money[p]){a.price=next;a.last=p;per[p].top=next;per[p].bid=true;turns[p]++;if(rule==="B-lite"&&!revealed[p]){revealed[p]=true;revealRound[p]=r+1;if(revealed.every(Boolean)&&allKnownRound==null)allKnownRound=r+1}}else{per[p].dropped=true;per[p].refused=next;a.live=a.live.filter(z=>z!==p);passes[p]++;dropSum[p]+=a.price}
   if(a.live.length<=1)break;let cur=p,gg=0;do{cur=(cur+1)%n}while(!a.live.includes(cur)&&gg++<20);if(cur===a.last)break;a.cur=cur;
  }
  const winner=a.price>0?(a.live.length===1?a.live[0]:a.last):-1;if(winner>=0){const val=total+T*v[lens[winner]],gain=val-a.price;money[winner]-=a.price;won[winner].push({val});lotWon[winner]++;pay[winner]+=a.price;net[winner]+=gain;if(a.price>val){over[winner]++;curse[winner]++}for(let p=0;p<n;p++){if(diag[p].used&&p===winner&&gain>=0)diag[p].good++;if(diag[p].used&&p!==winner&&(total+T*v[lens[p]]-a.price)<0)diag[p].avoid++;if(diag[p].used&&p===winner&&gain<0)diag[p].harm++}if(strats[winner].type==="S4"&&diag[winner].bt){diag[winner].bs++;diag[winner].bn+=gain}}
  const rec={v,total,w:winner,price:a.price,per:per.map(x=>({...x}))};hist.push(rec);for(let p=0;p<n;p++)if(per[p].bid){const j=lens[p],h=posHist[j];h.n++;h.top+=per[p].top;if(per[p].dropped)h.drop+=per[p].refused||0}if(rule==="B-history"&&histReadyRound==null&&posHist.every(x=>x.n>=2))histReadyRound=r+1;
  const distinct=Array.from(new Set(Array.from({length:n},(_,p)=>per[p].top>=8?lens[p]:-1).filter(x=>x>=0)));if(distinct.length>=2){info.multiHigh++;info.multiHighValue+=total}if(distinct.length>=c.NC-1&&distinct.length>=2)info.certainLots++;info.lots++;
 }
 const score=money.map((m,i)=>m+won[i].reduce((z,o)=>z+o.val,0)),order=[...score].sort((a,b)=>b-a),mx=order[0];for(let p=0;p<n;p++){const m=metrics[strats[p].type],rank=1+score.filter(x=>x>score[p]).length,ties=score.filter(x=>x===mx).length;m.games++;if(score[p]===mx)m.wins+=1/ties;m.rankSum+=rank;m.rankDist[rank-1]++;m.score+=score[p];m.score2+=score[p]*score[p];m.cash+=money[p];m.value+=won[p].reduce((z,o)=>z+o.val,0);m.leaderGap+=score[p]-mx;m.lotsWon+=lotWon[p];m.pay+=pay[p];m.net+=net[p];m.overpay+=over[p];m.curse+=curse[p];m.passes+=passes[p];m.dropSum+=dropSum[p];m.turns+=turns[p];const d=diag[p];m.estN+=d.n;m.estAbs+=d.abs;m.baseAbs+=d.base;m.infoUsed+=d.used;m.infoBetter+=d.better;m.goodBuy+=d.good;m.badAvoid+=d.avoid;m.infoHarm+=d.harm;m.distinguished+=d.dist;m.bluffTry+=d.bt;m.bluffStuck+=d.bs;m.bluffNet+=d.bn}
 info.games++;if(rule==="B-lite"){const cnt=revealed.filter(Boolean).length;info.revealCount+=cnt;info.never+=n-cnt;info.players+=n;info.allKnown+=cnt===n;info.bGames++;info.revealRoundSum+=revealRound.filter(x=>x!=null).reduce((a,b)=>a+b,0);info.revealedN+=revealRound.filter(x=>x!=null).length;if(allKnownRound!=null){info.allKnownRoundSum+=allKnownRound;info.allKnownRoundN++}}if(rule==="B-history"&&histReadyRound!=null){info.histReadySum+=histReadyRound;info.histReadyN++}
}
function finalize(m){const g=m.games,p=m.wins/g,se=Math.sqrt(Math.max(p*(1-p),1e-12)/g),avg=m.score/g,sd=Math.sqrt(Math.max(0,m.score2/g-avg*avg));return{games:g,winRate:p,winCI95:[Math.max(0,p-1.96*se),Math.min(1,p+1.96*se)],meanRank:m.rankSum/g,rankDistribution:m.rankDist.slice(0,6).map(x=>x/g),meanScore:avg,scoreSD:sd,meanCash:m.cash/g,meanAcquiredValue:m.value/g,meanLeaderGap:m.leaderGap/g,lotsPerGame:m.lotsWon/g,avgPrice:m.pay/Math.max(1,m.lotsWon),netPerWin:m.net/Math.max(1,m.lotsWon),overpayRate:m.overpay/Math.max(1,m.lotsWon),winnerCurseRate:m.curse/Math.max(1,m.lotsWon),passPerGame:m.passes/g,avgDrop:m.dropSum/Math.max(1,m.passes),bidTurnsPerGame:m.turns/g,estimateMAE:m.estAbs/Math.max(1,m.estN),baseEstimateMAE:m.baseAbs/Math.max(1,m.estN),estimateImprovement:m.baseAbs/Math.max(1,m.estN)-m.estAbs/Math.max(1,m.estN),infoUsePerGame:m.infoUsed/g,infoDecisionSuccess:m.infoBetter/Math.max(1,m.infoUsed),goodBuyPerGame:m.goodBuy/g,badAvoidPerGame:m.badAvoid/g,infoHarmPerGame:m.infoHarm/g,distinguishPerGame:m.distinguished/g,bluffPerGame:m.bluffTry/g,bluffStuckRate:m.bluffStuck/Math.max(1,m.bluffTry),bluffNetPerStuck:m.bluffNet/Math.max(1,m.bluffStuck)}}
function runCell(n,rule,kind,alpha,games,seed){const metrics={S0:newMetric(),S1:newMetric(),S2:newMetric(),S3:newMetric(),S4:newMetric()},info={revealCount:0,never:0,players:0,allKnown:0,bGames:0,games:0,multiHigh:0,multiHighValue:0,certainLots:0,lots:0,revealRoundSum:0,revealedN:0,allKnownRoundSum:0,allKnownRoundN:0,histReadySum:0,histReadyN:0};for(let i=0;i<games;i++)play(n,rule,kind,alpha,seed+i*17,seed+900000+i*31,metrics,info);const out={n,rule,kind,alpha,games,strategies:{}};for(const [k,m] of Object.entries(metrics))if(m.games)out.strategies[k]=finalize(m);out.info={bLiteRevealedPlayerRate:info.players?info.revealCount/info.players:null,bLiteNeverRevealedRate:info.players?info.never/info.players:null,bLiteAllKnownGameRate:info.bGames?info.allKnown/info.bGames:null,bLiteMeanRevealLot:info.revealedN?info.revealRoundSum/info.revealedN:null,bLiteMeanAllKnownLot:info.allKnownRoundN?info.allKnownRoundSum/info.allKnownRoundN:null,bHistoryMeanLotsToTwoSamplesEach:info.histReadyN?info.histReadySum/info.histReadyN:null,bHistoryReadyGameRate:info.histReadyN/info.games,multiPositionHighFreq:info.games?info.multiHigh/info.games:null,multiPositionHighTrueValue:info.multiHigh?info.multiHighValue/info.multiHigh:null,nearCertainSignalLotRate:info.certainLots/Math.max(1,info.lots)};return out}
function main(){const cells=[];const kinds=["mixed","vs:S0","vs:S1","vs:S2","vs:S4","all:S0","all:S1","all:S2","all:S3"];for(const rule of RULES)for(const kind of kinds)cells.push(runCell(4,rule,kind,.5,10000,41000+kinds.indexOf(kind)*1000));for(const rule of RULES)for(const a of ALPHAS)cells.push(runCell(4,rule,"vs:S2",a,10000,91000+Math.round(a*1000)));for(const n of [2,3,5,6])for(const rule of RULES)cells.push(runCell(n,rule,"mixed",.5,5000,120000+n*1000));const out={meta:{generatedAt:new Date().toISOString(),seedScheme:"fixed; identical lot/position seed by n/kind across rules",rules:"seri.html v1.4",constants:{SETUP,CMIN,CMAX,E,T},mainGames:10000,auxGames:5000},cells};fs.writeFileSync(path.join(__dirname,"seri_position_info_results.json"),JSON.stringify(out,null,2));console.log(`wrote ${cells.length} cells`)}
main();
